SELECT
       TBREGS.ID_PLANO,
       TAS.CD_SERVICO_OPCIONAL,
       TAS.DE_SERVICO_OPCIONAL AS SERVICO_OPCIONAL
FROM STG_PRODUTO.TB_REGS_PLANO TBREGS
INNER JOIN STG_PRODUTO.RL_REGS_PLANO_SERVICO_OPCIONAL REGPL ON TBREGS.ID_PLANO = REGPL.ID_PLANO
INNER JOIN STG_PRODUTO.TA_SERVICO_OPCIONAL TAS  ON REGPL.CD_SERVICO_OPCIONAL = TAS.CD_SERVICO_OPCIONAL
WHERE
  ROWNUM <= 5
